### ISSUE TITLE
No Zoom-Out Button

### ISSUE THREAD

**Issue by SongRb** [awonderfullife/Electronic-book-share-platform#1]
Branch: `UI_prototype`
I can click course map to zoom in, but i can't return to previous zoom level

**Comment by hawnzug** [comment]
@SongRb You can click somewhere out of the current circle to zoom out.
I only test it in Firefox 52.0.2...Maybe there are some compatibility issues.

**Comment by hawnzug** [comment]
If you can zoom out correctly in your browser, I will close this issue. And what's your opinion on #2?

**Comment by SongRb** [comment]
@hawnzug 
Chrome 57 64-bit
Internet Explorer 11
Worked Normally
