### ISSUE TITLE
Database API Not Working Properly

### ISSUE THREAD

**Issue by SongRb** [awonderfullife/Electronic-book-share-platform#11]
`get_EBook_FileStoredName(EBookID)` will raise an error if `EBookID` doesn't exist in table.  
Recommended: return `None` if non-existence

`  File "D:\Study\Software Engineering\Group Project\Electronic-book-share-platform\dataBaseSupport.py", line 518, in get_EBook_FileStoredName
    return [result_list[0][0].rstrip(' '), result_list[0][1].rstrip(' ')]
AttributeError: 'NoneType' object has no attribute 'rstrip'`

**Comment by awonderfullife** [comment]
this problem occur because there some data was not import into our database, I add some messures to avoid it =-=~~~
