### ISSUE TITLE
issue for API

### ISSUE THREAD

**Issue by awonderfullife** [awonderfullife/Electronic-book-share-platform#4]
I just wonder if the update user info api needed a int parameter "score " , I see it in the get User Info , but I can't finded it in update user info  @hawnzug

**Comment by SongRb** [comment]
@awonderfullife Maybe the Update User Information API is used for personal info modification by users themselves, therefore, the API with update user score can be used to do database hacking.

**Comment by hawnzug** [comment]
@SongRb Got it! The update api is used by front end. Users cannot modify their score anyway, so this api does not take score as its parameter.

**Comment by awonderfullife** [comment]
Fine, then I will close this issue. Any new api is needed for database, contact me~
