### ISSUE TITLE
Issue for database API support

### ISSUE THREAD

**Issue by awonderfullife** [awonderfullife/Electronic-book-share-platform#5]
From the requirement LuHua Jing edited in API for DataBase Wiki, I will begin to write these function   
1. two different function to get EBook information   
2. series of function that receive an EBookID as a parameter and some attribute that needed to modify for this Book such as score, rate, author, etc.   
However I think, the EBook information `download_time` shouldn't included in DataBase as it can get the time when related function is called, To obey object oriented principle, I think it should be created in other function.     
what's your opinion? @SongRb @Joshua1023

**Comment by SongRb** [comment]
In my opinion, the attribute `download_time` depends on network bandwidth and cannot be a constant. It is better that we add `file_size` to EBook information list.

**Comment by awonderfullife** [comment]
So you means that we estimate a average time for a Book from it file size, But I am wonder, whether could we get download time dynamicly from the time the function called and the time download finished, perhaps we should ask ZhuYang Wang for this ?  @SongRb

**Comment by SongRb** [comment]
@awonderfullife Got it! Estimated download time should be calculated by web page scripts

**Comment by awonderfullife** [comment]
So, we need your help  @hawnzug

**Comment by hawnzug** [comment]
I'm sorry about this question. Actually, this attribute should be named as `download_times` but not `download_time`. It's my fault.

**Comment by awonderfullife** [comment]
Oh, I understand! Thanks.   
interesting issues time to close it ~

**Comment by hawnzug** [comment]
Oh I think we should first modify the relating wiki and codes then close this issue.

**Comment by Joshua1023** [comment]
I will modify the api part later.

**Comment by Joshua1023** [comment]
Question:why do we use English instead of Chinese, just because it seems professional?

**Comment by SongRb** [comment]
@Joshua1023 Of Course! Absolutely! No Problem!

**Comment by hawnzug** [comment]
修改了前端 e74e1dd 和 [wiki](https://github.com/awonderfullife/Electronic-book-share-platform/wiki/API/c0a3a1e623264d5e77d10642c41fd88637e051ff)

**Comment by Joshua1023** [comment]
The api part and the wiki have been modified now.
