### ISSUE TITLE
Move to HTTPS Protocol

### ISSUE THREAD

**Issue by SongRb** [awonderfullife/Electronic-book-share-platform#6]
HTTPS is more secure than HTTP
> The protocol employs encryption to keep eavesdroppers from “hearing” your conversation. It also keeps a Man-in-the-Middle (MITM) hacker from hijacking your conversation. The hacker that perpetrates a MITM can feed you false info and gather info from you that you assume is protected. 
[Why the “s” in HTTPs is important](http://www.computerworld.com/article/3021276/mobile-security/why-the-s-in-https-is-important.html)

Although it seems that no hacker will be interested in our website, using HTTPS can still be a nice try.

**Comment by hawnzug** [comment]
Maybe after deployment......

**Comment by Faldict** [comment]
It is just a course project, why are you so serious?
