### ISSUE TITLE
Upload file dialog bug

### ISSUE THREAD

**Issue by SongRb** [awonderfullife/Electronic-book-share-platform#9]
@hawnzug   
The progress bar will be always at 60% no matter how many text box are filled.  
![snipaste_20170514_110001](https://cloud.githubusercontent.com/assets/15308237/26030927/b26550dc-3894-11e7-8249-7c972d26a17f.png)

**Comment by hawnzug** [comment]
This is not implemented. I will take this issue.

**Comment by hawnzug** [comment]
Fixed:  b229911
